// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MeasureDetection.djinni

#pragma once

#include "djinni_support.hpp"
#include "measure_reader.hpp"

namespace djinni_generated {

class NativeMeasureReader final : ::djinni::JniInterface<::sheetmusicreader::MeasureReader, NativeMeasureReader> {
public:
    using CppType = std::shared_ptr<::sheetmusicreader::MeasureReader>;
    using CppOptType = std::shared_ptr<::sheetmusicreader::MeasureReader>;
    using JniType = jobject;

    using Boxed = NativeMeasureReader;

    ~NativeMeasureReader();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMeasureReader>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMeasureReader>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMeasureReader();
    friend ::djinni::JniClass<NativeMeasureReader>;
    friend ::djinni::JniInterface<::sheetmusicreader::MeasureReader, NativeMeasureReader>;

};

}  // namespace djinni_generated
