// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MeasureDetection.djinni

#import <Foundation/Foundation.h>
@class SMRHelloWorld;


@interface SMRHelloWorld : NSObject

+ (nullable SMRHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

@end
