// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MeasureDetection.djinni

#import "SMRHelloWorld+Private.h"
#import "SMRHelloWorld.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SMRHelloWorld ()

- (id)initWithCpp:(const std::shared_ptr<::sheetmusicreader::HelloWorld>&)cppRef;

@end

@implementation SMRHelloWorld {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::sheetmusicreader::HelloWorld>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::sheetmusicreader::HelloWorld>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SMRHelloWorld *)create {
    try {
        auto objcpp_result_ = ::sheetmusicreader::HelloWorld::create();
        return ::djinni_generated::HelloWorld::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getHelloWorld {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_hello_world();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto HelloWorld::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto HelloWorld::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SMRHelloWorld>(cpp);
}

}  // namespace djinni_generated

@end
