// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MeasureDetection.djinni

#import <Foundation/Foundation.h>
@class SMRMeasureReader;


@interface SMRMeasureReader : NSObject

+ (nullable SMRMeasureReader *)Create;

- (void)DetectMeasure;

@end
