// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MeasureDetection.djinni

#include "measure_reader.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SMRMeasureReader;

namespace djinni_generated {

class MeasureReader
{
public:
    using CppType = std::shared_ptr<::sheetmusicreader::MeasureReader>;
    using CppOptType = std::shared_ptr<::sheetmusicreader::MeasureReader>;
    using ObjcType = SMRMeasureReader*;

    using Boxed = MeasureReader;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

