// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MeasureDetection.djinni

#import "SMRMeasureReader+Private.h"
#import "SMRMeasureReader.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SMRMeasureReader ()

- (id)initWithCpp:(const std::shared_ptr<::sheetmusicreader::MeasureReader>&)cppRef;

@end

@implementation SMRMeasureReader {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::sheetmusicreader::MeasureReader>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::sheetmusicreader::MeasureReader>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SMRMeasureReader *)Create {
    try {
        auto objcpp_result_ = ::sheetmusicreader::MeasureReader::Create();
        return ::djinni_generated::MeasureReader::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)DetectMeasure {
    try {
        _cppRefHandle.get()->DetectMeasure();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto MeasureReader::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto MeasureReader::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SMRMeasureReader>(cpp);
}

}  // namespace djinni_generated

@end
